package:
  create:
    max_package_size: "1000000000"
    set:
      repo: "https://repo1.dso.mil/big-bang/product/packages/gitlab.git"
      tag: 6.11.3-bb.0
      name: gitlab
      namespace: gitlab
      path: chart
  deploy:
    set:
      domain: ###ZARF_VAR_DOMAIN###
