apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: "###ZARF_TMPL_NAME###"
  namespace: bigbang
spec:
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
    /**/*.sh
  interval: 10m
  url: "###ZARF_TMPL_REPO###"
  ref:
    tag: "###ZARF_TMPL_TAG###"
