apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: "###ZARF_VAR_NAME###"
  namespace: bigbang
spec:
  ignore: |
    # exclude file extensions
    /**/*.md
    /**/*.txt
    /**/*.sh
  interval: 10m
  url: "###ZARF_VAR_REPO###"
  ref:
    tag: "###ZARF_VAR_TAG###"
