package:
  create:
    max_package_size: "1000000000"
    set:
      repo: "https://repo1.dso.mil/big-bang/product/packages/gitlab-runner"
      tag: 0.51.0-bb.2
      name: gitlab-runner
      namespace: gitlab
      path: chart
